name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: hub login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: docker build . --file Dockerfile --tag dockertn3/openjdk8-alpine-msfonts:$(date +%s)
    - name: Docker push
      run: docker push ${{ secrets.DOCKER_USER }}/openjdk8-alpine-msfonts
